AleedTiendaShopping/AleedTiendaShopping/Controllers/DashboardController.cs
using AleedTiendaShopping.Data;
using AleedTiendaShopping.Enums;
using AleedTiendaShopping.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace AleedTiendaShopping.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DashboardController : Controller
    {
        private readonly DataContext _context;
        private readonly IUserHelper _userHelper;

        public DashboardController(DataContext context, IUserHelper userHelper)
        {
            _context = context;
            _userHelper = userHelper;
        }
        public async Task<IActionResult> Index()
        {
            ViewBag.UsersCount = _context.Users.Count();
            ViewBag.ProductsCount = _context.Products.Count();
            ViewBag.NewOrdersCount = _context.Sales.Where(o => o.OrderStatus == OrderStatus.Nuevo).Count();
            ViewBag.ConfirmedOrdersCount = _context.Sales.Where(o => o.OrderStatus == OrderStatus.Confirmado).Count();

            return View(await _context.TemporalSales
                    .Include(u => u.User)
                    .Include(p => p.Product).ToListAsync());
        }
    }

}

AleedTiendaShopping/AleedTiendaShopping/Controllers/OrdersController.cs
using AleedTiendaShopping.Data;
using AleedTiendaShopping.Data.Entities;
using AleedTiendaShopping.Enums;
using AleedTiendaShopping.Helpers;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Vereyon.Web;

namespace AleedTiendaShopping.Controllers
{
   
    public class OrdersController : Controller
    {
        private readonly DataContext _context;
        private readonly IFlashMessage _flashMessage;
        private readonly IOrdersHelper _ordersHelper;

        public OrdersController(DataContext context, IFlashMessage flashMessage, IOrdersHelper ordersHelper)
        {
            _context = context;
            _flashMessage = flashMessage;
            _ordersHelper=ordersHelper;
        }

        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Index()
        {
            return View(await _context.Sales
                .Include(s => s.User)
                .Include(s => s.SaleDetails)
                .ThenInclude(sd => sd.Product)
                .ToListAsync());
        }
       
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Sale sale = await _context.Sales
                .Include(s => s.User)
                .Include(s => s.SaleDetails)
                .ThenInclude(sd => sd.Product)
                .ThenInclude(p => p.ProductImages)
                .FirstOrDefaultAsync(s => s.Id == id);
            if (sale == null)
            {
                return NotFound();
            }

            return View(sale);
        }
       
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Dispatch(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Sale sale = await _context.Sales.FindAsync(id);
            if (sale == null)
            {
                return NotFound();
            }

            if (sale.OrderStatus != OrderStatus.Nuevo)
            {
                _flashMessage.Danger("Solo se pueden despachar pedidos que estén en estado 'nuevo'.");
            }
            else
            {
                sale.OrderStatus = OrderStatus.Despachado;
                _context.Sales.Update(sale);
                await _context.SaveChangesAsync();
                _flashMessage.Confirmation("El estado del pedido ha sido cambiado a 'despachado'.");
            }

            return RedirectToAction(nameof(Details), new { Id = sale.Id });
        }
       
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Send(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Sale sale = await _context.Sales.FindAsync(id);
            if (sale == null)
            {
                return NotFound();
            }

            if (sale.OrderStatus != OrderStatus.Despachado)
            {
                _flashMessage.Danger("Solo se pueden enviar pedidos que estén en estado 'despachado'.");
            }
            else
            {
                sale.OrderStatus = OrderStatus.Enviado;
                _context.Sales.Update(sale);
                await _context.SaveChangesAsync();
                _flashMessage.Confirmation("El estado del pedido ha sido cambiado a 'enviado'.");
            }

            return RedirectToAction(nameof(Details), new { Id = sale.Id });
        }
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Confirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Sale sale = await _context.Sales.FindAsync(id);
            if (sale == null)
            {
                return NotFound();
            }

            if (sale.OrderStatus != OrderStatus.Enviado)
            {
                _flashMessage.Danger("Solo se pueden confirmar pedidos que estén en estado 'enviado'.");
            }
            else
            {
                sale.OrderStatus = OrderStatus.Confirmado;
                _context.Sales.Update(sale);
                await _context.SaveChangesAsync();
                _flashMessage.Confirmation("El estado del pedido ha sido cambiado a 'confirmado'.");
            }

            return RedirectToAction(nameof(Details), new { Id = sale.Id });
        }
        [Authorize(Roles = "Admin")]

        public async Task<IActionResult> Cancel(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Sale sale = await _context.Sales.FindAsync(id);
            if (sale == null)
            {
                return NotFound();
            }

            if (sale.OrderStatus == OrderStatus.Cancelado)
            {
                _flashMessage.Danger("No se puede cancelar un pedido que esté en estado 'cancelado'.");
            }
            else
            {
                await _ordersHelper.CancelOrderAsync(sale.Id);
                _flashMessage.Confirmation("El estado del pedido ha sido cambiado a 'cancelado'.");
            }

            return RedirectToAction(nameof(Details), new { Id = sale.Id });
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> MyOrders()
        {
            return View(await _context.Sales
                .Include(s => s.User)
                .Include(s => s.SaleDetails)
                .ThenInclude(sd => sd.Product)
                .Where(s => s.User.UserName == User.Identity.Name)
                .ToListAsync());
        }

        [Authorize(Roles = "User")]
        public async Task<IActionResult> MyDetails(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Sale sale = await _context.Sales
                .Include(s => s.User)
                .Include(s => s.SaleDetails)
                .ThenInclude(sd => sd.Product)
                .ThenInclude(p => p.ProductImages)
                .FirstOrDefaultAsync(s => s.Id == id);
            if (sale == null)
            {
                return NotFound();
            }

            return View(sale);
        }

    }

}

AleedTiendaShopping/AleedTiendaShopping/Controllers/UsersController.cs
using AleedTiendaShopping.Common;
using AleedTiendaShopping.Data;
using AleedTiendaShopping.Data.Entities;
using AleedTiendaShopping.Enums;
using AleedTiendaShopping.Helpers;
using AleedTiendaShopping.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Text.RegularExpressions;
using Vereyon.Web;

namespace AleedTiendaShopping.Controllers
{
    public class UsersController:Controller
    {
        private readonly IUserHelper _userHelper;
        private readonly DataContext _context;
        private readonly ICombosHelper _combosHelper;
        private readonly IBlobHelper _blobHelper;
        private readonly IMailHelper _mailHelper;
        private readonly IFlashMessage _flashMessage;


        public UsersController(IUserHelper userHelper, DataContext context, ICombosHelper combosHelper, IBlobHelper blobHelper,
            IMailHelper mailHelper, IFlashMessage  flashMessage)
        {
            _userHelper = userHelper;
            _context = context;
            _combosHelper = combosHelper;
            _blobHelper = blobHelper;
            _mailHelper = mailHelper;
            _flashMessage = flashMessage;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Users
                .Include(u => u.City)
                .ThenInclude(c => c.State)
                .ThenInclude(s => s.Country)
                .ToListAsync());
        }

       

        public async Task<IActionResult> Create()
        {
            AddUserViewModel model = new AddUserViewModel
            {
                Id = Guid.Empty.ToString(),
                Countries = await _combosHelper.GetComboCountriesAsync(),
                States = await _combosHelper.GetComboStatesAsync(0),
                Cities = await _combosHelper.GetComboCitiesAsync(0),
                UserType = UserType.Admin,
            };

            return View(model);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AddUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                // subir imaghen azure
                //Guid imageId = Guid.Empty;

                //if (model.ImageFile != null)
                //{
                //    imageId = await _blobHelper.UploadBlobAsync(model.ImageFile, "users");
                //}

                //validacion de imagenes
                string filename = "";
                if (model.ImageFile == null)
                {

                    filename = "noexiste.png";
                }
                else
                {
                    filename = model.ImageFile.FileName;
                }


                if (!Regex.IsMatch(filename.ToLower(), @"^.*\.(jpg|gif|png|jpeg)$"))
                {
                    _flashMessage.Danger("la imagen debe ser tipo .jpg .gift .png .jpeg");
                    model.Countries = await _combosHelper.GetComboCountriesAsync();
                    model.States = await _combosHelper.GetComboStatesAsync(model.CountryId);
                    model.Cities = await _combosHelper.GetComboCitiesAsync(model.StateId);
                    return View(model);

                }

                //cedula no repetida
                User usertwo = await _context.Users
           .FirstOrDefaultAsync(x => x.Document == model.Document);
                if (usertwo != null)
                {
                    _flashMessage.Danger( "Documento de identidad ya esta registrado");
                    model.Countries = await _combosHelper.GetComboCountriesAsync();
                    model.States = await _combosHelper.GetComboStatesAsync(model.CountryId);
                    model.Cities = await _combosHelper.GetComboCitiesAsync(model.StateId);
                    return View(model);
                }

                //almacenamiento foto
                string ruta = "";
                string path = "";
                string pic = "";
                if (model.ImageFile != null)
                {

                    pic = Path.GetFileName(model.Document.ToString() + ".png");

                    path = Path.Combine("wwwroot\\images\\users", pic);
                    ruta = "https://localhost:7116/images/users/" + pic;

                    using (FileStream stream = new FileStream(path, FileMode.Create))
                    {
                        model.ImageFile.CopyTo(stream);
                        model.ImageFullPath = ruta;

                    }


                }

                //creacion
                User user = await _userHelper.AddUserAsync(model);
                if (user == null)
                {
                    _flashMessage.Danger("Este correo ya está siendo usado.");
                    model.Countries = await _combosHelper.GetComboCountriesAsync();
                    model.States = await _combosHelper.GetComboStatesAsync(model.CountryId);
                    model.Cities = await _combosHelper.GetComboCitiesAsync(model.StateId);
                    return View(model);
                }


                string myToken = await _userHelper.GenerateEmailConfirmationTokenAsync(user);
                string tokenLink = Url.Action("ConfirmEmail", "Account", new
                {
                    userid = user.Id,
                    token = myToken
                }, protocol: HttpContext.Request.Scheme);

                Response response = _mailHelper.SendMail(
                    $"{model.FirstName} {model.LastName}",
                    model.Username,
                    "Shopping - Confirmación de Email",
                    $"<h1>Shopping - Confirmación de Email</h1>" +
                        $"Para habilitar el usuario por favor hacer clicn en el siguiente link:, " +
                        $"<p><a href = \"{tokenLink}\">Confirmar Email</a></p>");
                if (response.IsSuccess)
                {
                    _flashMessage.Info( "Las instrucciones para habilitar el usuario han sido enviadas al correo.");
                    return View(model);
                }

                _flashMessage.Danger(string.Empty, response.Message);

            }
            model.Countries = await _combosHelper.GetComboCountriesAsync();
            model.States = await _combosHelper.GetComboStatesAsync(model.CountryId);
            model.Cities = await _combosHelper.GetComboCitiesAsync(model.StateId);
            return View(model);
        }


        public JsonResult? GetStates(int countryId)
        {
            Country? country = _context.Countries
                .Include(c => c.States)
                .FirstOrDefault(c => c.Id == countryId);
            if (country == null)
            {
                return null;
            }

            return Json(country.States.OrderBy(d => d.Name));
        }

        public JsonResult? GetCities(int stateId)
        {
            State? state = _context.States
                .Include(s => s.Cities)
                .FirstOrDefault(s => s.Id == stateId);
            if (state == null)
            {
                return null;
            }

            return Json(state.Cities.OrderBy(c => c.Name));
        }

       
    }

}

AleedTiendaShopping/AleedTiendaShopping/Views/Shared/_AddOrEditDialog.cshtml
<!--modal placeholder. Also you can place this modal form in the _Layout.cshtml-->
<div class="modal fade in" tabindex="-1" role="dialog" data-bs-backdrop="static" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header header__color">
                <h5 class="modal-title text-white"></h5>
                <button type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close">                   
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

AleedTiendaShopping/AleedTiendaShopping/Views/Shared/_BusyIndicatorPartial.cshtml
<div class="loading text-danger">
    Loading&#8230;
</div>

AleedTiendaShopping/AleedTiendaShopping/Views/Shared/_DeleteDialog.cshtml
<div class="modal fade in" id="deleteDialog" tabindex="-1" role="dialog" data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header header__color">
                <h5 class="modal-title" id="exampleModalLabel">Borrar Registro</h5>
            </div>
            <div class="modal-body">
                <p>¿Estas seguro de querer borrar este registro?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal">No</button>
                <button type="button" class="btn btn-danger" id="btnYesDelete">Sí</button>
            </div>
        </div>
    </div>
</div>

<style>
    .header__color {
    background-image: linear-gradient(to left, #43CBFF, #9708CC) !important;
    color:#fff !important;
    }
    .modal{
        margin:auto!important;
        
    }

    .modal-content{
   margin:auto !important;
    width: 70% !important;
    max-width: 70% !important;
    
       }

}
</style>

AleedTiendaShopping/AleedTiendaShopping/Views/Shared/_DeleteDialogEdit.cshtml
<div class="modal fade in" id="deleteDialog" tabindex="-1" role="dialog" data-bs-backdrop="static" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header bg-blue-gradient">
                <h5 class="modal-title" id="exampleModalLabel">Borrar Registro</h5>
            </div>
            <div class="modal-body">
                <p>¿Estas seguro de querer borrar este registro?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"> </i> No</button>

                <button asp-action="Delete" type="button"  asp-route-id="Id" class="btn btn-danger" id="btnYesDelete"><i class="fa fa-check-circle"> </i> Sí</button>
            </div>
        </div>
    </div>
</div>

AleedTiendaShopping/AleedTiendaShopping/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Shopping</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
@*    <link rel="stylesheet" href="~/lib/font-awesome/css/all.min.css" />
*@    

   <link rel="stylesheet" href="~/lib/datatables/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="~/lib/jqueryui/jquery-ui.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Shooping.styles.css" asp-append-version="true" />
</head>

<body>
    <!--menu-->
    <div class="contenedor" >
  <nav class="menu">
        <section class="menu__container">
            <img  class="menu__logo" src=~/images/logomarca.png/>

            <ul class="menu__links">
                <li class="menu__item">
                    <a  asp-controller="Home" asp-action="Inicio" class="menu__link">Inicio</a>
                </li>
       @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li class="menu__item menu__item--show">
                            <a href="#" class="menu__link">Administración <img src="~/images/arrow.svg" class="menu__arrow"></a>
    
                    <ul class="menu__nesting">
                        <li class="menu__inside">
                            <a asp-area="" asp-controller="Dashboard" asp-action="Index" class="menu__link menu__link--inside"> Dashboard</a>
                        </li>
                        <li class="menu__inside">
                            <a asp-area="" asp-controller="Categories" asp-action="Index" class="menu__link menu__link--inside"> Categorías</a>
                        </li>
                        <li class="menu__inside">
                            <a asp-area="" asp-controller="Countries" asp-action="Index" class="menu__link menu__link--inside"> Países</a>
                        </li>
                        <li class="menu__inside">
                            <a asp-area="" asp-controller="Orders" asp-action="Index" class="menu__link menu__link--inside">Pedidos</a>
                        </li>
                         <li class="menu__inside">
                            <a asp-area="" asp-controller="Products" asp-action="Index" class="menu__link menu__link--inside"> Productos</a>
                        </li>
                         <li class="menu__inside">
                            <a asp-area="" asp-controller="Users" asp-action="Index" class="menu__link menu__link--inside"> Usuarios</a>
                        </li>
                    </ul>
                </li>
    }
              @if (User.Identity.IsAuthenticated && User.IsInRole("User"))
                        {
                             <li class="menu__item">
                    <a  asp-area="" asp-controller="Orders" asp-action="MyOrders" class="menu__link">Mis Pedidos</a>
                </li>
                            
                        }

             @if (User.Identity.IsAuthenticated)
                        {
                            <li class="menu__item menu__item--show">
                                <a href="#" class="menu__link">Mi perfíl <img src="~/images/arrow.svg" class="menu__arrow"></a>
                                <ul class="menu__nesting">
                                     <li class="menu__inside">
                                       <a asp-area="" asp-area="" asp-controller="Account" asp-action="ChangeUser" class="menu__link menu__link--inside"> Mi Información</a>
                                    </li>
                                    <li class="menu__inside">
                                       <a asp-area="" asp-area="" asp-controller="Account" asp-action="ChangePassword" class="menu__link menu__link--inside">Cambiar Contraseña</a>
                                    </li>
                                </ul>
                                
                            </li>
                            <li class="menu__item">
                                <a class="menu__link" asp-area="" asp-controller="Account" asp-action="Logout">Cerrar Sesión</a>
                            </li>
                        }
                        else
                        {
                            <li class="menu__item">
                                <a class="menu__link" asp-area="" asp-controller="Account" asp-action="Login">Iniciar Sesión</a>
                            </li>
                        }
    
               
    
            </ul>

            <div class="menu__hamburguer">
                <img src="~/images/menu.svg" class="menu__img">
            </div>
        </section>

      
    </nav>
  </div> 
    <!--indicador-->
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_BusyIndicatorPartial" />
            @RenderBody()
        </main>
    </div>

  <!--  footer --->

  <div class="footer-basic" id="footer">
        <footer>
            <div class="social">
                <a href="https://www.instagram.com/aleed.tiendadesentimientos/?hl=es-la" target="_blank"><i class="fa-brands fa-instagram iconoredes"></i></a>
                <a href="https://api.whatsapp.com/send?phone=573195605554&text=Hola!%20Quiero%20Comprar%20un%20regalo%F0%9F%8E%81%F0%9F%8E%81%F0%9F%8E%81" target="_blank"><i class="fa-brands fa-whatsapp iconoredes"></i></i></a>
                <a href="https://www.facebook.com/people/Aleed-tienda-de-sentimientos/100064868476103/" target="_blank"><i class="fa-brands fa-facebook iconoredes"></i></i></a>
            </div>
            <div class="list-inline">
                 <p class="text__focus">ALEED - TIENDA DE SENTIMIENTOS </p>            
                <p>Hay detalles  que roban sonrisas  e invaden  el corazón. Y con Aleed tienda de sentimientos, seguro que lo encuentras.  </p>            
            <p class="copyright">Alejandro Galeano © 2022 -  &copy;  <a class="privacy-pol" asp-area="" asp-controller="Home" asp-action="Privacy">Políticas de Privacidad</a></p>
            </div>
            
        </footer>
    </div>

 <script src="~/js/menuresponsivedos.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jasny/jasny-bootstrap.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" ></script>
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/jquery-ui/jquery-ui.min.js"></script>
@*    <script src="~/lib/font-awesome/js/all.min.js"></script>*@
    <script>
        function displayBusyIndicator() {
            $('.loading').show();
        }
    </script>

    <script>
        $(window).on('beforeunload', function () {
            displayBusyIndicator();
        });
    </script>

    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AleedTiendaShopping/AleedTiendaShopping/Views/Shared/_ProducDialog.cshtml
<!--modal placeholder. Also you can place this modal form in the _Layout.cshtml-->
<div class="modal fade in" tabindex="-1" role="dialog" data-bs-backdrop="static" id="form-modal">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header header__color">
                <h5 class="modal-title text-white"></h5>
                <button id="refresh" type="button" class="btn-close text-white" data-bs-dismiss="modal" aria-label="Close">                   
                </button>
            </div>
            <div class="modal-body">
            </div>
        </div>
    </div>
</div>

<script>
    let refresh = document.getElementById('refresh');
refresh.addEventListener('click', _ => {
            location.reload();
})
</script>

AleedTiendaShopping/AleedTiendaShopping/Views/Shared/_User.cshtml
@model AleedTiendaShopping.Models.EditUserViewModel

<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="Document" class="control-label"></label>
            <input asp-for="Document" class="form-control" />
            <span asp-validation-for="Document" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="FirstName" class="control-label"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="LastName" class="control-label"></label>
            <input asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="Address" class="control-label"></label>
            <input asp-for="Address" class="form-control" />
            <span asp-validation-for="Address" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="PhoneNumber" class="control-label"></label>
            <input asp-for="PhoneNumber" class="form-control" />
            <span asp-validation-for="PhoneNumber" class="text-danger"></span>
        </div>
    </div>    
    <div class="col-md-6">
        <div class="form-group">
            <label asp-for="ImageFile" class="control-label"></label>
            <input asp-for="ImageFile" class="form-control" type="file" />
            <span asp-validation-for="ImageFile" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="CountryId" class="control-label"></label>
            <select asp-for="CountryId" asp-items="Model.Countries" class="form-control"></select>
            <span asp-validation-for="CountryId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="StateId" class="control-label"></label>
            <select asp-for="StateId" asp-items="Model.States" class="form-control"></select>
            <span asp-validation-for="StateId" class="text-danger"></span>
        </div>

        <div class="form-group">
            <span class="required">*</span>
            <label asp-for="CityId" class="control-label"></label>
            <select asp-for="CityId" asp-items="Model.Cities" class="form-control"></select>
            <span asp-validation-for="CityId" class="text-danger"></span>
        </div>
    </div>    
</div>